# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.1.1
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: 61719308+ChinhDangg@users.noreply.github.com
author_name: Chinh Dang
cloud_provider: none
preset_name: production
project_name: algorand-hackathon-frontend

